# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robogui_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1196, 900)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.walking_btn = QtWidgets.QPushButton(Dialog)
        self.walking_btn.setFlat(False)
        self.walking_btn.setObjectName("walking_btn")
        self.horizontalLayout.addWidget(self.walking_btn)
        self.leg_btn = QtWidgets.QPushButton(Dialog)
        self.leg_btn.setObjectName("leg_btn")
        self.horizontalLayout.addWidget(self.leg_btn)
        self.body_btn = QtWidgets.QPushButton(Dialog)
        self.body_btn.setObjectName("body_btn")
        self.horizontalLayout.addWidget(self.body_btn)
        self.joints_btn = QtWidgets.QPushButton(Dialog)
        self.joints_btn.setObjectName("joints_btn")
        self.horizontalLayout.addWidget(self.joints_btn)
        self.cute_actions_btn = QtWidgets.QPushButton(Dialog)
        self.cute_actions_btn.setObjectName("cute_actions_btn")
        self.horizontalLayout.addWidget(self.cute_actions_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.tabWidget_plots = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_plots.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_plots.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.tabWidget_plots.setObjectName("tabWidget_plots")
        self.verticalLayout_5.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_control_device = QtWidgets.QLabel(Dialog)
        self.label_control_device.setMinimumSize(QtCore.QSize(30, 35))
        self.label_control_device.setMaximumSize(QtCore.QSize(180, 35))
        self.label_control_device.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_control_device.setObjectName("label_control_device")
        self.horizontalLayout_2.addWidget(self.label_control_device)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.tabWidget_plots.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.walking_btn, self.leg_btn)
        Dialog.setTabOrder(self.leg_btn, self.body_btn)
        Dialog.setTabOrder(self.body_btn, self.joints_btn)
        Dialog.setTabOrder(self.joints_btn, self.cute_actions_btn)
        Dialog.setTabOrder(self.cute_actions_btn, self.tabWidget_plots)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RoboGUI"))
        self.walking_btn.setText(_translate("Dialog", "Walking"))
        self.leg_btn.setText(_translate("Dialog", "Legs"))
        self.body_btn.setText(_translate("Dialog", "Body"))
        self.joints_btn.setText(_translate("Dialog", "Joints"))
        self.cute_actions_btn.setText(_translate("Dialog", "Cute Actions"))
        self.label_11.setText(_translate("Dialog", "Control"))
        self.label_10.setText(_translate("Dialog", "Signals"))
        self.label_12.setText(_translate("Dialog", "Chosen Signals"))
        self.label_4.setText(_translate("Dialog", "Control Device:"))
        self.label_control_device.setText(_translate("Dialog", "PC"))
