general:
  frequency: 40
topics:
  cmd_vel: "gui/cmd_vel"
  cmd_pose: "gui/cmd_pose"
  cmd_ef_pose: "gui/ef_position/command"
  cmd_joint_pos: "gui/joint_group_position_controller/command" 
  status: "gui/status"
  cur_device: "cur_device"
  joint_state: "joint_state"
  imu_data: "imu/data"
  temperature_data: "imu/temp"
gait:
  max_speed_x: 0.3
  max_speed_y: 0.2
  max_speed_z: 0.8
pose:
  max_angle_x: 0.33
  max_angle_y: 0.33
  max_angle_z: 0.33
  max_lin_x: 0.1
  max_lin_y: 0.1
  max_lin_z: 0.1
  min_lin_z: 0.15
ef:
  max_pos_x: 0.05
  max_pos_y: 0.05
  max_pos_z: 0.05
  min_pos_z: 0.05
joints:
  max_abad: 1.57
  max_hip: 1.57
  max_knee: 1.57
modes:
  walk: 0
  ef: 1
  body: 2
  joint: 3