"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class servo_cmd_msg(object):
    __slots__ = ["timestamp", "position", "velocity", "torque", "kp", "kd"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, [12], [12], [12], [12], [12]]

    def __init__(self):
        self.timestamp = 0.0
        self.position = [ 0.0 for dim0 in range(12) ]
        self.velocity = [ 0.0 for dim0 in range(12) ]
        self.torque = [ 0.0 for dim0 in range(12) ]
        self.kp = [ 0.0 for dim0 in range(12) ]
        self.kd = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(servo_cmd_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.timestamp))
        buf.write(struct.pack('>12f', *self.position[:12]))
        buf.write(struct.pack('>12f', *self.velocity[:12]))
        buf.write(struct.pack('>12f', *self.torque[:12]))
        buf.write(struct.pack('>12f', *self.kp[:12]))
        buf.write(struct.pack('>12f', *self.kd[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != servo_cmd_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return servo_cmd_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = servo_cmd_msg()
        self.timestamp = struct.unpack(">f", buf.read(4))[0]
        self.position = struct.unpack('>12f', buf.read(48))
        self.velocity = struct.unpack('>12f', buf.read(48))
        self.torque = struct.unpack('>12f', buf.read(48))
        self.kp = struct.unpack('>12f', buf.read(48))
        self.kd = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if servo_cmd_msg in parents: return 0
        tmphash = (0xaccd131c2302bee2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if servo_cmd_msg._packed_fingerprint is None:
            servo_cmd_msg._packed_fingerprint = struct.pack(">Q", servo_cmd_msg._get_hash_recursive([]))
        return servo_cmd_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

