frequency: 50
ros_joint_state_topic: "joint_states"
lcm_joint_state_topic: "SERVO_STATE"

joint_order: [3, 5, 4, 9, 11, 10, 0, 2, 1, 6, 8, 7]
joint_directions: [ 1,  -1,  -1, 1,  1,  1, -1,  -1,  -1, -1,  1,  1]
